---
- name: Dev environemnt
  hosts: all
  any_errors_fatal: true
  become: True
  roles:
    - { role: system, tags: ['system'] }
    - { role: yum, tags: ['yum'] }

- name: Dev docker oracle env
  hosts: dbdev
  any_errors_fatal: true
  become: True
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: docker-oracledb-image, tags: ['oracledb-image'] }
    - { role: docker-oracledb-create, tags: ['oracledb-create'] }
    - { role: docker-oracledb-opatch, tags: ['oracledb-opatch'] }
    - { role: docker-oracledb-dbpatch, tags: ['oracledb-dbpatch'] }
    - { role: docker-oracledb-init, tags: ['oracledb-init'] }