
- name: Remove dbora service
  systemd:
    name: dbora.service
    enabled: no
    state: stopped
  failed_when: false

- name: Stop all oracle process
  shell: pkill -9 -u `id -u oracle` -e -c || echo no processes

- name: Delete oracle directories
  shell: rm -fR /tmp/11gR2.rsp /u01 /tmp/OraInstall* /home/oracle/* /etc/init.d/dbora /var/lock/subsys/dbora /etc/oraInst.loc /etc/oratab /lib/systemd/system/dbora.service /etc/systemd/system/dbora.service

- name: Remove old install directories
  shell: rm -fR client/ d* examples/* g* examples/
  args:
    chdir: "{{ oracle_install_file_directory }}"

- name: remove oracle user
  user:
    name: oracle
    update_password: always
    password: "{{system_oracle_user_password}}"
    state: absent
    remove: yes

- name: remove oracle-rdbms-server-11gR2-preinstall package
  yum:
    name: oracle-rdbms-server-11gR2-preinstall
    state: absent

- name: reboot server
  shell: sleep 5 && shutdown -r now "Triggered by Ansible"
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for ssh port
  local_action:
    wait_for host={{ ansible_host }}
    state=started port=22
    timeout=900
    connect_timeout=30
    delay=30
  become: false